services:
  frontend:
    build:
      context: .
    container_name: seebus_frontend
    restart: always
    environment:
      - VITE_API_URL=http://seebus.local/api
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seebus_frontend.rule=Host(`seebus.local`) && !PathPrefix(`/api`)"
      - "traefik.http.services.seebus_frontend.loadbalancer.server.port=5173"

networks:
  proxy_net:
    external: true
    name: ${PROXY_NETWORK:-proxy}
