services:
  app:
    build:
      context: .
    container_name: seebus_app
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./src:/var/www
      - data_seebus_vendor:/var/www/vendor
      - data_seebus_storage:/var/www/storage/framework
      - ./src/storage:/var/www/storage
    networks:
      - seebus_net
      - proxy_net

  webserver:
    image: nginx:alpine
    container_name: seebus_nginx
    restart: always
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./src:/var/www:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/storage:/var/www/storage:ro
    depends_on:
      - app
    networks:
      - seebus_net
      - proxy_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seebus.rule=Host(`seebus.local`)"
      - "traefik.http.services.seebus.loadbalancer.server.port=80"

volumes:
  data_seebus_vendor:
  data_seebus_storage:

networks:
  seebus_net:
    external: true
    name: ${DOCKER_NETWORK:-lalapo}
  proxy_net:
    external: true
    name: ${PROXY_NETWORK:-proxy}